### ISSUE TITLE
ccl_chrome_indexeddb fails on Python 3.9.15 packaged with Anki 2.1.66

### ISSUE THREAD

**Issue by abdnh** [abdnh/anki-copycat-importer#5]
When running with Anki 2.1.66, this error is thrown:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-23 13:41:13
Add-ons possibly involved: ⁨AnkiApp Importer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\main.py", line 38, in on_done
    count, warnings = fut.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\main.py", line 32, in start_importing
    importer = AnkiAppImporter(mw, path, path_type)
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\ankiapp_importer.py", line 335, in __init__
    self.indexeddb_reader._read(
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\ankiapp_importer.py", line 260, in _read
    for record in (
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_chromium_indexeddb.py", line 820, in iterate_records
    yield from self._raw_db.iterate_records(
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_chromium_indexeddb.py", line 625, in iterate_records
    value = deserializer.read()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 627, in read
    return self._read_object()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 611, in _read_object
    tag, o = self._read_object_internal()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 602, in _read_object_internal
    value = func()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 401, in _read_js_object
    for key, value in self._read_js_object_properties(Constants.token_kEndJSObject):
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 391, in _read_js_object_properties
    value = self._read_object()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 611, in _read_object
    tag, o = self._read_object_internal()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 602, in _read_object_internal
    value = func()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 401, in _read_js_object
    for key, value in self._read_js_object_properties(Constants.token_kEndJSObject):
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 391, in _read_js_object_properties
    value = self._read_object()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 611, in _read_object
    tag, o = self._read_object_internal()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 602, in _read_object_internal
    value = func()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 449, in _read_js_dense_array
    result[i] = self._read_object()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 611, in _read_object
    tag, o = self._read_object_internal()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 602, in _read_object_internal
    value = func()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 401, in _read_js_object
    for key, value in self._read_js_object_properties(Constants.token_kEndJSObject):
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 391, in _read_js_object_properties
    value = self._read_object()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 611, in _read_object
    tag, o = self._read_object_internal()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 602, in _read_object_internal
    value = func()
  File "D:\dev\anki\addons\AnkiApp-importer\build\t\addons21\2072125761\vendor\ccl_v8_value_deserializer.py", line 463, in _read_js_dense_array
    raise ValueError("Property count mismatch")
ValueError: Property count mismatch
```

The error doesn't occur in Python 3.9.13.

We may need to [limit ccl_chrome_indexeddb to Python 3.10](https://github.com/cclgroupltd/ccl_chrome_indexeddb#python-versions).

**Comment by abdnh** [comment]
No longer valid as of version 3.0.0
