### ISSUE TITLE
Database is locked. Problem with migrating all decks from AnkiApp

### ISSUE THREAD

**Issue by lemonglutton** [abdnh/anki-copycat-importer#7]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "C:\Users\Jola\AppData\Roaming\Anki2\addons21\2072125761\gui\dialog.py", line 54, in on_done
    count, warnings = fut.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\Jola\AppData\Roaming\Anki2\addons21\2072125761\gui\dialog.py", line 48, in start_importing
    importer = self.importer_class(**options)
  File "C:\Users\Jola\AppData\Roaming\Anki2\addons21\2072125761\importers\ankiapp.py", line 322, in __init__
    if not self.appdata.sqlite_dbs:
  File "functools", line 993, in __get__
  File "C:\Users\Jola\AppData\Roaming\Anki2\addons21\2072125761\appdata.py", line 46, in sqlite_dbs
    for row in conn.execute("select origin from Databases"):
sqlite3.OperationalError: database is locked

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Copycat Importer AnkiAppAnkiPro ['2072125761', 2024-03-18T20:03, 'None', '']

===IDs of active AnkiWeb add-ons===
2072125761

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by abdnh** [comment]
Make sure AnkiApp is closed and try disabling antivirus software.
